### ISSUE TITLE
Tests are cancelled by timeout

### ISSUE THREAD

**Issue by vagabondan** [Yandex-Practicum/tests-selfmade-project-3-public#1]
Example:
https://github.com/vagabondan/nado_sdelat_idealno/actions/runs/6696822682/job/18195380071

```
Run bash tests-selfmade-project-3-public/run.sh
  bash tests-selfmade-project-3-public/run.sh
  shell: /usr/bin/bash -e {0}
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@[2](https://github.com/vagabondan/nado_sdelat_idealno/actions/runs/6696822682/job/18195380071#step:6:2). I'll try to do my best with it!

> canvas@2.9.0 install /home/runner/work/nado_sdelat_idealno/nado_sdelat_idealno/tests-selfmade-project-[3](https://github.com/vagabondan/nado_sdelat_idealno/actions/runs/6696822682/job/18195380071#step:6:3)-public/node_modules/canvas
> node-pre-gyp install --fallback-to-build

[canvas] Success: "/home/runner/work/nado_sdelat_idealno/nado_sdelat_idealno/tests-selfmade-project-3-public/node_modules/canvas/build/Release/canvas.node" is installed via remote

> puppeteer@15.[4](https://github.com/vagabondan/nado_sdelat_idealno/actions/runs/6696822682/job/18195380071#step:6:5).0 install /home/runner/work/nado_sdelat_idealno/nado_sdelat_idealno/tests-selfmade-project-3-public/node_modules/puppeteer
> node install.js


Chromium (1011831) downloaded to /home/runner/work/nado_sdelat_idealno/nado_sdelat_idealno/tests-selfmade-project-3-public/node_modules/puppeteer/.local-chromium/linux-1011831
npm WARN tests-selfmade-project-3@1.0.0 No description
npm WARN tests-selfmade-project-3@1.0.0 No repository field.

added 386 packages from 29[5](https://github.com/vagabondan/nado_sdelat_idealno/actions/runs/6696822682/job/18195380071#step:6:6) contributors and audited 38[6](https://github.com/vagabondan/nado_sdelat_idealno/actions/runs/6696822682/job/18195380071#step:6:7) packages in 14.043s

80 packages are looking for funding
  run `npm fund` for details

found 15 vulnerabilities (2 low, 11 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at pptr://__puppeteer_evaluation_script__:1:103
    at Array.map (<anonymous>)
    at pptr://__puppeteer_evaluation_script__:1:82
    at ExecutionContext._ExecutionContext_evaluate (file:///home/runner/work/nado_sdelat_idealno/nado_sdelat_idealno/tests-selfmade-project-3-public/node_modules/puppeteer/lib/esm/puppeteer/common/ExecutionContext.js:282:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (file:///home/runner/work/nado_sdelat_idealno/nado_sdelat_idealno/tests-selfmade-project-3-public/node_modules/puppeteer/lib/esm/puppeteer/common/ExecutionContext.js:114:16)
    at async checkBodyElements (file:///home/runner/work/nado_sdelat_idealno/nado_sdelat_idealno/tests-selfmade-project-3-public/src/lib.js:2:[7](https://github.com/vagabondan/nado_sdelat_idealno/actions/runs/6696822682/job/18195380071#step:6:8)24)
    at async Promise.all (index 4)
    at async runTests (file:///home/runner/work/nado_sdelat_idealno/nado_sdelat_idealno/tests-selfmade-project-3-public/src/tests.js:1:6[9](https://github.com/vagabondan/nado_sdelat_idealno/actions/runs/6696822682/job/18195380071#step:6:10)4)
    at async app (file:///home/runner/work/nado_sdelat_idealno/nado_sdelat_idealno/tests-selfmade-project-3-public/src/index.js:1:[23](https://github.com/vagabondan/nado_sdelat_idealno/actions/runs/6696822682/job/18195380071#step:6:24)1)
Error: The operation was canceled.
```

**Comment by vagabondan** [comment]
Problem is here, this filter is not enough:
`filter(a=>'#text'!==a.nodeName)`
should be changed to: check tagName at element
`filter(a=>'#text'!==a.nodeName&&a.tagName)`
